name: Günlük Dengetv54 Güncellemesi

on:
  schedule:
    - cron: "0 */2 * * *"  # Her 2 saatte bir
  workflow_dispatch:        # Manuel tetikleme için

permissions:
  contents: write

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Playwright kurulum (isteğe bağlı ama önerilir)
      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium || true

      - name: Run auto discovery + generate M3U
        run: |
          python src/dengetv54_auto.py

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/dengetv54.m3u cache.json dengetv_auto.log || true
          git commit -m "🔁 Otomatik M3U güncellemesi $(date '+%Y-%m-%d %H:%M:%S')" || true
          git push
